steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: src\electron'
  inputs:
    TargetFolder: src\electron

- script: |
    cd src\electron
    node script/yarn.js install --frozen-lockfile
  displayName: 'Yarn install'

- powershell: |
    $localArtifactPath = "$pwd\dist.zip"
    $serverArtifactPath = "$env:APPVEYOR_URL/buildjobs/$env:APPVEYOR_JOB_ID/artifacts/dist.zip"
    Invoke-RestMethod -Method Get -Uri $serverArtifactPath -OutFile $localArtifactPath -Headers @{ "Authorization" = "Bearer $env:APPVEYOR_TOKEN" }
    & "${env:ProgramFiles(x86)}\7-Zip\7z.exe" x -osrc\out\Default -y $localArtifactPath
  displayName: 'Download and extract dist.zip for test'
  env:
    APPVEYOR_TOKEN: $(APPVEYOR_TOKEN)

- powershell: |
    $localArtifactPath = "$pwd\src\out\Default\shell_browser_ui_unittests.exe"
    $serverArtifactPath = "$env:APPVEYOR_URL/buildjobs/$env:APPVEYOR_JOB_ID/artifacts/shell_browser_ui_unittests.exe"
    Invoke-RestMethod -Method Get -Uri $serverArtifactPath -OutFile $localArtifactPath -Headers @{ "Authorization" = "Bearer $env:APPVEYOR_TOKEN" }
  displayName: 'Download and extract native test executables for test'
  env:
    APPVEYOR_TOKEN: $(APPVEYOR_TOKEN)

- powershell: |
    $localArtifactPath = "$pwd\ffmpeg.zip"
    $serverArtifactPath = "$env:APPVEYOR_URL/buildjobs/$env:APPVEYOR_JOB_ID/artifacts/ffmpeg.zip"
    Invoke-RestMethod -Method Get -Uri $serverArtifactPath -OutFile $localArtifactPath -Headers @{ "Authorization" = "Bearer $env:APPVEYOR_TOKEN" }
    & "${env:ProgramFiles(x86)}\7-Zip\7z.exe" x -osrc\out\ffmpeg $localArtifactPath
  displayName: 'Download and extract ffmpeg.zip for test'
  env:
    APPVEYOR_TOKEN: $(APPVEYOR_TOKEN)

- powershell: |
    $localArtifactPath = "$pwd\src\node_headers.zip"
    $serverArtifactPath = "$env:APPVEYOR_URL/buildjobs/$env:APPVEYOR_JOB_ID/artifacts/node_headers.zip"
    Invoke-RestMethod -Method Get -Uri $serverArtifactPath -OutFile $localArtifactPath -Headers @{ "Authorization" = "Bearer $env:APPVEYOR_TOKEN" }
    cd src
    & "${env:ProgramFiles(x86)}\7-Zip\7z.exe" x -y node_headers.zip
  displayName: 'Download node headers for test'
  env:
    APPVEYOR_TOKEN: $(APPVEYOR_TOKEN)

- powershell: |
    $localArtifactPath = "$pwd\src\out\Default\electron.lib"
    $serverArtifactPath = "$env:APPVEYOR_URL/buildjobs/$env:APPVEYOR_JOB_ID/artifacts/electron.lib"
    Invoke-RestMethod -Method Get -Uri $serverArtifactPath -OutFile $localArtifactPath -Headers @{ "Authorization" = "Bearer $env:APPVEYOR_TOKEN" }
  displayName: 'Download electron.lib for test'
  env:
    APPVEYOR_TOKEN: $(APPVEYOR_TOKEN)

- powershell: |
    New-Item src\out\Default\gen\node_headers\Release -Type directory
    Copy-Item -path src\out\Default\electron.lib -destination src\out\Default\gen\node_headers\Release\node.lib
  displayName: 'Setup node headers'

- script: |
    cd src
    set npm_config_nodedir=%cd%\out\Default\gen\node_headers
    set npm_config_arch=arm64
    cd electron
    # Use the spec runner to prepare for testing   
    node script/yarn test --onlyPrepForRunning    
    cd ..
    # CalculateNativeWinOcclusion is disabled due to https://bugs.chromium.org/p/chromium/issues/detail?id=1139022
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-app-spec.ts --disable-features=CalculateNativeWinOcclusion
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-auto-updater-spec.ts --disable-features=CalculateNativeWinOcclusion
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-autoupdater-darwin-spec.ts --disable-features=CalculateNativeWinOcclusion
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-browser-view-spec.ts --disable-features=CalculateNativeWinOcclusion
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-browser-window-spec.ts --disable-features=CalculateNativeWinOcclusion
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-content-tracing-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-context-bridge-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-crash-reporter-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-debugger-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-deprecate-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-desktop-capturer-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-dialog-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-global-shortcut-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-in-app-purchase-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-ipc-main-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-ipc-renderer-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-ipc-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-menu-item-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-menu-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-native-theme-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-net-log-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-net-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-notification-dbus-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-notification-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-power-monitor-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-power-save-blocker-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-protocol-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-screen-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-service-workers-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-session-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-shell-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-subframe-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-system-preferences-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-touch-bar-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-tray-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-view-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-web-contents-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-web-contents-view-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-web-frame-main-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-web-frame-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\api-web-request-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\asar-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\autofill-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\chromium-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\crash-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\extensions-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\guest-window-manager-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\internal-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\logging-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\modules-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\node-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\release-notes-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\security-warnings-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\spellchecker-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\types-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\version-bump-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\visibility-state-spec.ts --disable-features=CalculateNativeWinOcclusion 
    out\Default\electron.exe electron\spec-main --trace-uncaught --enable-logging --files electron\spec-main\webview-spec.ts --disable-features=CalculateNativeWinOcclusion
  displayName: 'Run Electron Main process tests'
  env:
    ELECTRON_ENABLE_STACK_DUMPING: true
    ELECTRON_OUT_DIR: Default
    IGNORE_YARN_INSTALL_ERROR: 1
    ELECTRON_TEST_RESULTS_DIR: junit
    MOCHA_MULTI_REPORTERS: 'mocha-junit-reporter, tap'
    MOCHA_REPORTER: mocha-multi-reporters

- script: |
    cd src
    set npm_config_nodedir=%cd%\out\Default\gen\node_headers
    set npm_config_arch=arm64
    out\Default\electron.exe electron\spec --enable-logging --disable-features=CalculateNativeWinOcclusion
  displayName: 'Run Electron Remote based tests'
  env:
    ELECTRON_OUT_DIR: Default
    IGNORE_YARN_INSTALL_ERROR: 1
    ELECTRON_TEST_RESULTS_DIR: junit
    MOCHA_MULTI_REPORTERS: 'mocha-junit-reporter, tap'
    MOCHA_REPORTER: mocha-multi-reporters
  condition: always()    

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/src/junit/'
  condition: always()

- script: |
    cd src
    echo "Verifying non proprietary ffmpeg"
    python electron\script\verify-ffmpeg.py --build-dir out\Default --source-root %cd% --ffmpeg-path out\ffmpeg
  displayName: 'Verify ffmpeg'

- powershell: |
    Get-Process | Where Name –Like "electron*" | Stop-Process
    Get-Process | Where Name –Like "msedge*" | Stop-Process
  displayName: 'Kill processes left running from last test run'
  condition: always()

- powershell: |
    Remove-Item -path $env:APPDATA/Electron* -Recurse -Force -ErrorAction Ignore
  displayName: 'Delete user app data directories'
  condition: always()
